name: video_plus
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  fijkplayer: any
  visibility_detector: any
  flick_video_player: any
  video_player: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:



